### ISSUE TITLE
🐛 EntityValuePicker: plugin fails to recognize single entity

### ISSUE THREAD

**Issue by art10m** [web-seven/backstage-plugins#39]
# EntityValuePicker from `@web-seven/backstage-plugin-scaffolder-extensions` does not work when only one entity of a given kind exists in the Backstage catalog.

## Issue details:
When using the `EntityValuePicker` plugin in my Backstage frontend application, it fails to work properly if there is only one entity of the specified kind in the catalog. The selected value seems to be captured, but the form doesn't recognize it. However, when I add a second entity of the same kind, the plugin starts functioning as expected.

### Example Configuration:
```yaml
environment:
  title: Environment
  type: string
  ui:field: EntityValuePicker
  ui:options:
    catalogFilter:
      - kind: Environment
    valuesSchema:
      name: metadata.name
    template: "{{ name }}"
```
In the above example, if only one Environment entity is present, the plugin doesn't register it correctly. Once a second entity of the same kind is added, it starts working.

## Todo:
- [ ] Investigate the issue with EntityValuePicker when only one entity is available in the catalog.
- [ ] Ensure that the plugin properly handles cases with only a single entity.
## Version:
@web-seven/backstage-plugin-scaffolder-extensions: 0.0.11
