### ISSUE TITLE
🐛 bug(scaffolder-extensions): EntityValuePicker return empty value

### ISSUE THREAD

**Issue by evghen1** [web-seven/backstage-plugins#76]
### Plugin Name

scaffolder-extensions

### 📜 Description

While testing EntityValuePicker templates found value returned is empty.

### 👍 Expected behavior

EntityValuePicker shall return selected values rendered using template.

### 👎 Actual Behavior with Screenshots

```
 ui:field: EntityValuePicker
          ui:options:
            catalogFilter:
              - kind: Package
            valuesSchema:
              package: metadata.name
              tag: spec.tags
            template: "{{ package }}:{{ tag }}"
```
this options return ":" string

### 👟 Reproduction steps

Try to get picked value.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/web-seven/backstage-plugins/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
