### ISSUE TITLE
🐛 bug (scaffolder-extensions): State management & required

### ISSUE THREAD

**Issue by matdtr** [web-seven/backstage-plugins#96]
### Plugin Name

scaffolder-extensions

### 📜 Description

Using `MultiEntity*` has two side effects:
- if I go on review page, going back the choice is not kept in the UI component
- if `required` the MultiEntity* seems never be filled even if entity are chosen. 
( i think this can be solved easily changing the TextField required to `required? autocompleteValue.length === 0 : required` )

Finally but this is an issue on backstage using the `MultiEntityObjectPicker` is the selection of entities is >=1 the review page has the full objects and the scroll to the create button is infinite 

### 👍 Expected behavior

For point 1, it should keep the chosen values
For point 2, if entity is selected the template can move to next step

### 👎 Actual Behavior with Screenshots

For point 1, going to review step and then going back in order to edit looses the selection. The same happens if executing the template back again from task page.
For point 2, setting the input as required will make impossible to go to next step of the template. 

### 👟 Reproduction steps

Create a template with this configuration:

```  
parameters:
  - title: Fill in some info
    required:
    - title
    - users
    properties:
      title:
        title: title
        type: string
        description: title
        ui:autofocus: true
        ui:options:
          rows: 5
      users:
        title: Users
        type: array
        description: users
        ui:field: MultiEntityObjectPicker 
        ui:options:
          catalogFilter:
            kind: [ Users ]
          labelVariant: primaryTitle
 steps:
  - id: debug-list-workspace
    name: debug-workspace
    action: debug:log
    input:
      message: ${{ parameters | dump }}
```  

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/web-seven/backstage-plugins/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
