### ISSUE TITLE
🐛 bug (scaffolder-extensions): Review not using custom buttons presentations

### ISSUE THREAD

**Issue by evghen1** [web-seven/backstage-plugins#98]
### Plugin Name

scaffolder-extensions

### 📜 Description

Review step component do not use presentations customization for buttons.

### 👍 Expected behavior

when template has this presentations configs they shall be used on review step rendering:
https://backstage.io/docs/features/software-templates/writing-templates/#presentation

### 👎 Actual Behavior with Screenshots

Currently review step display just default/hardcoded labels of buttons

### 👟 Reproduction steps

add this presentation into template specs and go to review:
```
spec:
  owner: scaffolder/maintainers
  type: website
  presentation:
    buttonLabels:
      backButtonText: 'Return'
      createButtonText: 'Update'
      reviewButtonText: 'Verify'
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/web-seven/backstage-plugins/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
